### ISSUE TITLE
Hoping for transparency options

### ISSUE THREAD

**Issue by 111nation** [WinterSunset95/WhatsGo#13]
Amazing project just opened it up, havent fully used it yet but one thing that's bothering me is the lack of transparency.
Hopefully that will be a feature in the future!

**Comment by WinterSunset95** [comment]
Hi, unfortunately we have no way to handle transparency through the libraries that we're using for this project.

However WhatsGo will inherit the transparency of whatever terminal you're using.
I use alacritty with transparency set through picom. As you can see I have a transclucent background.

![image](https://github.com/user-attachments/assets/231dc0ff-2c79-434a-96d4-610cde31d23b)

**Comment by 111nation** [comment]
Oh Ok thank you for letting me know, I am also realizing that my opaque effect is also unintended because I was using Kali Linux on Windows subsystem for Linux on cmd. And I don't see a way of tracking if the host's Windows terminal emulator is transparent or not. Thank you though! Good project really enjoyed!

**Comment by WinterSunset95** [comment]
Thank you so much
